import React from "react";

export default function page() {
  return (
    <div className="ml-64 p-4">
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
      <h1>hola</h1>
    </div>
  );
}
